---
- name: Common Tasks
  hosts: all
  become: true
  roles:
    - common

- name: Master Tasks
  hosts: master
  become: true
  roles:
    - master

#- name: Local Tasks
#  hosts: master
#  become: true
#  roles:
#    - local

- name: Worker Tasks
  hosts: worker
  become: true
  roles:
    - worker
