---
- name: Copy and start service playbook
  hosts: ec2
  become: true
  vars:
    jar_file_path: "/var/lib/jenkins/workspace/AWS-deployment/target/spark-lms-0.0.1-SNAPSHOT.jar"
    excute_path: "/home/ec2-user/spark-lms-0.0.1-SNAPSHOT.jar"
    service_name: "app.service"
  tasks:
    - name: Copy JAR file to slave
      copy:
        src: "{{ jar_file_path }}"
        dest: "/home/ec2-user"
        mode: 0644
      register: copy_result

    - name: Install Java 11 Amazon Corretto development package
      dnf:
        name: java-11-amazon-corretto-devel
        state: present

    - name: Create systemd service for Spark LMS
      template:
        src: app.service.j2
        dest: /etc/systemd/system/app.service


    - name: Reload systemd manager configuration
      command: "systemctl daemon-reload"
      
    - name: Stop and disable App service
      systemd:
        name: app
        state: stopped

    - name: Restart the service
      systemd:
        name: "{{ service_name }}"
        state: restarted
