---
- name: Copy and start service playbook
  hosts: ec2
  become: true
  vars:
    jar_file_path: "/var/lib/jenkins/workspace/AWS-deployment/target/spark-lms-0.0.1-SNAPSHOT.jar"
    service_name: "app.service"

  tasks:
    - name: Copy JAR file to slave
      copy:
        src: "{{ jar_file_path }}"
        dest: "/home/ec2-user"
        mode: 0644
      register: copy_result

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes


    - name: Start the service
      systemd:
        name: "{{ service_name }}"
        state: started
        enabled: yes
      when: copy_result.changed

    - name: Restart the service
      systemd:
        name: "{{ service_name }}"
        state: restarted
