---
- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Add current user to Docker group
  command: sudo usermod -aG docker $USER

- name: Install dependencies
  command: sudo snap install docker

- name: Start and enable Docker service
  service:
    name: docker
    state: started
    enabled: yes

